resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
    clean: true
  - task: TerraformInstaller@0
    displayName: Install Terraform 1.0.3
    inputs:
      terraformVersion: 1.0.3
  - task: TerraformTaskV2@2
    displayName: 'Terraform : init'
    inputs:
      backendServiceArm: fec0b219-a96f-4884-a16d-4ef8a32ceffb
      backendAzureRmResourceGroupName: DevOpsPOC2RG
      backendAzureRmStorageAccountName: devopspoc2storage1
      backendAzureRmContainerName: tfstateblobpoc2
      backendAzureRmKey: terraform.tfstate
- job: QualityTestJob
  dependsOn: Job_1
  condition: succeeded()
  displayName: Run TFSec
  steps:
  - bash: |
      docker run --rm -t -v $(System.DefaultWorkingDirectory): liamg/tfsec